In [8]:
import numpy as np
new_label = np.array([])

In [11]:
new_label = np.append(new_label,1)

In [12]:
new_label


array([1.])

In [ ]:
import torch
from torch import nn

In [ ]:
input = torch.zeros(3, 5, requires_grad=True)

In [86]:
a = torch.randn(5)

In [88]:
torch.log(a)

tensor([    nan,     nan,     nan, -1.1023, -0.7548])

In [84]:
a = torch.randn(5)
a

torch.log(a)
tensor([ nan,  nan,  nan,  nan,  nan])



In [85]:
np.log(k)

/home/jongsu/.pyenv/versions/anaconda3-4.2.0/lib/python3.5/site-packages/ipykernel/__main__.py:1: RuntimeWarning: divide by zero encountered in log
  if __name__ == '__main__':


array([      -inf, 1.38629436, 1.38629436])

In [90]:


loss = nn.CrossEntropyLoss()

target = torch.tensor([ 0.,  4.,  4.])


In [91]:
torch.log(target)

tensor([   -inf,  1.3863,  1.3863])

In [58]:
input

tensor([[ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.]])

In [6]:
target

tensor([ 0,  4,  4])

In [59]:
np.shape(target)

torch.Size([3])

In [2]:
import numpy as np
import sys
import os
#import tensorflow as tf

import io
from gensim.models import word2vec

from io import StringIO
from pprint import pprint

from nltk.tokenize import word_tokenize
import nltk
import torch
import torch.nn as nn
from torch import optim

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
import torch.utils.data
from torchvision import transforms, utils
from torch.utils.data import DataLoader

In [42]:
a = torch.tensor([[ 0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
          0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
          0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
          0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
          0.,  0.,  0.,  0.],
        [ 0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
          0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
          0.,  0.,  0.,  0.],
        [ 0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
          0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
          0.,  0.,  0.,  0.],
        [ 0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
          0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
          0.,  0.,  0.,  0.],
        [ 0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
          0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
          0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
          0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,
          0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
          0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
          0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
          0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,
          0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
          0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,
          0.,  0.,  0.,  0.]])

In [43]:
np.shape(a)

torch.Size([10, 28])

In [36]:

input_v = torch.randn(10,1,100)

criterian = nn.MSELoss()

class Gru(nn.Module):
    
    def __init__(self, hidden_dim):
        super(Gru, self).__init__()
        self.gru = nn.GRU(100,100,bidirectional = True)
        self.inh = torch.zeros(2, 1, 100)
        self.nn = nn.Linear(200,100)
        self.nn2 = nn.Linear(100,28)
        
    def init_hidden(self):
        return torch.zeros(2, 1, 100)
   
    def forward(self, sentence):  
        output,hidden = gru(sentence,self.inh)
        output = self.nn(output.view(10,200))
        output2 = self.nn2(output)
        return output2,hidden

In [37]:
gru1 = Gru(100)

In [40]:
np.shape(output)

torch.Size([10, 28])

In [67]:
optimizer1 = optim.SGD(gru1.parameters(), lr=0.1, weight_decay=1e-4)

In [73]:
i = 0
while(i < 1000):
    i = i + 1
    output,_ = gru1(input_v)
    loss = criterian(output,a)
    optimizer1.zero_grad()
    loss.backward()
    optimizer1.step()
    if i == 1000:
        print(loss)

tensor(1.00000e-05 *
       5.7007)


In [54]:
sent_1 = makesent_gru(100,True).cuda()
last_sent_1 = last_sent_net().cuda()
Gru1 = Gru(tagset,100).cuda()

NameError: name 'makesent_gru' is not defined

In [1]:
import torch
import torch.autograd as autograd
import torch.nn as nn
import torch.optim as optim

torch.manual_seed(1)


In [2]:
def argmax(vec):
    # return the argmax as a python int
    _, idx = torch.max(vec, 1)
    return idx.item()


def prepare_sequence(seq, to_ix):
    idxs = [to_ix[w] for w in seq]
    return torch.tensor(idxs, dtype=torch.long)


# Compute log sum exp in a numerically stable way for the forward algorithm
def log_sum_exp(vec):
    max_score = vec[0, argmax(vec)]
    max_score_broadcast = max_score.view(1, -1).expand(1, vec.size()[1])
    return max_score + \
        torch.log(torch.sum(torch.exp(vec - max_score_broadcast)))

In [3]:
class BiLSTM_CRF(nn.Module):

    def __init__(self, vocab_size, tag_to_ix, embedding_dim, hidden_dim):
        super(BiLSTM_CRF, self).__init__()
        self.embedding_dim = embedding_dim
        self.hidden_dim = hidden_dim
        self.vocab_size = vocab_size
        self.tag_to_ix = tag_to_ix
        self.tagset_size = len(tag_to_ix)

        self.word_embeds = nn.Embedding(vocab_size, embedding_dim)
        self.lstm = nn.LSTM(embedding_dim, hidden_dim // 2,
                            num_layers=1, bidirectional=True)

        # Maps the output of the LSTM into tag space.
        self.hidden2tag = nn.Linear(hidden_dim, self.tagset_size)

        # Matrix of transition parameters.  Entry i,j is the score of
        # transitioning *to* i *from* j.
        self.transitions = nn.Parameter(
            torch.randn(self.tagset_size, self.tagset_size))

        # These two statements enforce the constraint that we never transfer
        # to the start tag and we never transfer from the stop tag
        self.transitions.data[tag_to_ix[START_TAG], :] = -10000
        self.transitions.data[:, tag_to_ix[STOP_TAG]] = -10000

        self.hidden = self.init_hidden()

    def init_hidden(self):
        return (torch.randn(2, 1, self.hidden_dim // 2),
                torch.randn(2, 1, self.hidden_dim // 2))

    def _forward_alg(self, feats):
        # Do the forward algorithm to compute the partition function
        init_alphas = torch.full((1, self.tagset_size), -10000.)
        # START_TAG has all of the score.
        init_alphas[0][self.tag_to_ix[START_TAG]] = 0.

        # Wrap in a variable so that we will get automatic backprop
        forward_var = init_alphas

        # Iterate through the sentence
        for feat in feats:
            alphas_t = []  # The forward tensors at this timestep
            for next_tag in range(self.tagset_size):
                # broadcast the emission score: it is the same regardless of
                # the previous tag
                emit_score = feat[next_tag].view(
                    1, -1).expand(1, self.tagset_size)
                # the ith entry of trans_score is the score of transitioning to
                # next_tag from i
                trans_score = self.transitions[next_tag].view(1, -1)
                # The ith entry of next_tag_var is the value for the
                # edge (i -> next_tag) before we do log-sum-exp
                next_tag_var = forward_var + trans_score + emit_score
                # The forward variable for this tag is log-sum-exp of all the
                # scores.
                alphas_t.append(log_sum_exp(next_tag_var).view(1))
            forward_var = torch.cat(alphas_t).view(1, -1)
        terminal_var = forward_var + self.transitions[self.tag_to_ix[STOP_TAG]]
        alpha = log_sum_exp(terminal_var)
        return alpha

    def _get_lstm_features(self, sentence):
        self.hidden = self.init_hidden()
        embeds = self.word_embeds(sentence).view(len(sentence), 1, -1)
        lstm_out, self.hidden = self.lstm(embeds, self.hidden)
        lstm_out = lstm_out.view(len(sentence), self.hidden_dim)
        lstm_feats = self.hidden2tag(lstm_out)
        return lstm_feats

    def _score_sentence(self, feats, tags):
        # Gives the score of a provided tag sequence
        score = torch.zeros(1)
        tags = torch.cat([torch.tensor([self.tag_to_ix[START_TAG]], dtype=torch.long), tags])
        for i, feat in enumerate(feats):
            score = score + \
                self.transitions[tags[i + 1], tags[i]] + feat[tags[i + 1]]
        score = score + self.transitions[self.tag_to_ix[STOP_TAG], tags[-1]]
        return score

    def _viterbi_decode(self, feats):
        backpointers = []

        # Initialize the viterbi variables in log space
        init_vvars = torch.full((1, self.tagset_size), -10000.)
        init_vvars[0][self.tag_to_ix[START_TAG]] = 0

        # forward_var at step i holds the viterbi variables for step i-1
        forward_var = init_vvars
        for feat in feats:
            bptrs_t = []  # holds the backpointers for this step
            viterbivars_t = []  # holds the viterbi variables for this step

            for next_tag in range(self.tagset_size):
                # next_tag_var[i] holds the viterbi variable for tag i at the
                # previous step, plus the score of transitioning
                # from tag i to next_tag.
                # We don't include the emission scores here because the max
                # does not depend on them (we add them in below)
                next_tag_var = forward_var + self.transitions[next_tag]
                best_tag_id = argmax(next_tag_var)
                bptrs_t.append(best_tag_id)
                viterbivars_t.append(next_tag_var[0][best_tag_id].view(1))
            # Now add in the emission scores, and assign forward_var to the set
            # of viterbi variables we just computed
            forward_var = (torch.cat(viterbivars_t) + feat).view(1, -1)
            backpointers.append(bptrs_t)

        # Transition to STOP_TAG
        terminal_var = forward_var + self.transitions[self.tag_to_ix[STOP_TAG]]
        best_tag_id = argmax(terminal_var)
        path_score = terminal_var[0][best_tag_id]

        # Follow the back pointers to decode the best path.
        best_path = [best_tag_id]
        for bptrs_t in reversed(backpointers):
            best_tag_id = bptrs_t[best_tag_id]
            best_path.append(best_tag_id)
        # Pop off the start tag (we dont want to return that to the caller)
        start = best_path.pop()
        assert start == self.tag_to_ix[START_TAG]  # Sanity check
        best_path.reverse()
        return path_score, best_path

    def neg_log_likelihood(self, sentence, tags):
        feats = self._get_lstm_features(sentence)
        forward_score = self._forward_alg(feats)
        gold_score = self._score_sentence(feats, tags)
        return forward_score - gold_score

    def forward(self, sentence):  # dont confuse this with _forward_alg above.
        # Get the emission scores from the BiLSTM
        lstm_feats = self._get_lstm_features(sentence)

        # Find the best path, given the features.
        score, tag_seq = self._viterbi_decode(lstm_feats)
        return score, tag_seq

In [8]:
tags

['B', 'I', 'O', 'O', 'O', 'O', 'B']

In [7]:
tags[-1]

'B'

In [6]:
tag_to_ix[STOP_TAG]

4

In [ ]:
self.transitions[self.tag_to_ix[STOP_TAG], tags[-1]]

In [5]:
START_TAG = "<START>"
STOP_TAG = "<STOP>"
EMBEDDING_DIM = 5
HIDDEN_DIM = 4

# Make up some training data
training_data = [(
    "the wall street journal reported today that apple corporation made money".split(),
    "B I I I O O O B I O O".split()
), (
    "georgia tech is a university in georgia".split(),
    "B I O O O O B".split()
)]

word_to_ix = {}
for sentence, tags in training_data:
    for word in sentence:
        if word not in word_to_ix:
            word_to_ix[word] = len(word_to_ix)

tag_to_ix = {"B": 0, "I": 1, "O": 2, START_TAG: 3, STOP_TAG: 4}

model = BiLSTM_CRF(len(word_to_ix), tag_to_ix, EMBEDDING_DIM, HIDDEN_DIM)
optimizer = optim.SGD(model.parameters(), lr=0.01, weight_decay=1e-4)

# Check predictions before training
with torch.no_grad():
    precheck_sent = prepare_sequence(training_data[0][0], word_to_ix)
    precheck_tags = torch.tensor([tag_to_ix[t] for t in training_data[0][1]], dtype=torch.long)
    print(model(precheck_sent))

# Make sure prepare_sequence from earlier in the LSTM section is loaded
for epoch in range(
        300):  # again, normally you would NOT do 300 epochs, it is toy data
    for sentence, tags in training_data:
        # Step 1. Remember that Pytorch accumulates gradients.
        # We need to clear them out before each instance
        model.zero_grad()

        # Step 2. Get our inputs ready for the network, that is,
        # turn them into Tensors of word indices.
        sentence_in = prepare_sequence(sentence, word_to_ix)
        targets = torch.tensor([tag_to_ix[t] for t in tags], dtype=torch.long)

        # Step 3. Run our forward pass.
        print(loss)
        loss = model.neg_log_likelihood(sentence_in, targets)

        # Step 4. Compute the loss, gradients, and update the parameters by
        # calling optimizer.step()
        loss.backward()
        optimizer.step()

# Check predictions after training
with torch.no_grad():
    precheck_sent = prepare_sequence(training_data[0][0], word_to_ix)
    print(model(precheck_sent))
# We got it!


(tensor(9.2679), [1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])
tensor([ 0.4140])
tensor([ 12.1252])
tensor([ 6.4185])
tensor([ 12.1535])
tensor([ 6.2530])
tensor([ 12.1136])
tensor([ 6.1449])
tensor([ 11.6606])
tensor([ 5.9908])
tensor([ 11.7309])
tensor([ 6.1294])
tensor([ 11.5203])
tensor([ 5.7167])
tensor([ 11.4807])
tensor([ 5.9719])
tensor([ 11.1596])
tensor([ 5.7693])
tensor([ 11.1812])
tensor([ 5.9796])
tensor([ 10.9413])
tensor([ 5.8421])
tensor([ 10.9456])
tensor([ 5.5421])
tensor([ 10.9473])
tensor([ 5.8403])
tensor([ 10.7281])
tensor([ 5.5389])
tensor([ 10.4887])
tensor([ 5.5332])
tensor([ 10.3875])
tensor([ 5.5609])
tensor([ 10.1276])
tensor([ 5.6570])
tensor([ 10.1859])
tensor([ 5.2119])
tensor([ 9.9699])
tensor([ 5.2201])
tensor([ 10.0854])
tensor([ 5.6123])
tensor([ 9.7510])
tensor([ 5.5170])
tensor([ 9.7477])
tensor([ 5.1390])
tensor([ 9.8829])
tensor([ 5.1448])
tensor([ 9.7941])
tensor([ 4.9904])
tensor([ 9.5157])
tensor([ 5.2309])
tensor([ 9.4689])
tensor([ 4.8448])
tensor([ 9.5

In [ ]:
new iter
cal grad..
tensor([ 794.2930], device='cuda:0')
cal grad..
tensor([ 768.5750], device='cuda:0')
cal grad..
tensor([ 772.2324], device='cuda:0')
cal grad..
tensor([ 767.0294], device='cuda:0')
cal grad..
tensor([ 704.7906], device='cuda:0')
cal grad..
tensor([ 648.1509], device='cuda:0')
cal grad..
tensor([ 681.5404], device='cuda:0')
cal grad..
tensor([ 751.5012], device='cuda:0')
cal grad..
tensor([ 814.5165], device='cuda:0')
cal grad..
tensor([ 910.2877], device='cuda:0')
cal grad..
tensor([ 817.8049], device='cuda:0')
cal grad..
tensor([ 755.5457], device='cuda:0')
cal grad..
tensor([ 876.5235], device='cuda:0')
cal grad..
tensor([ 684.6308], device='cuda:0')
cal grad..
tensor([ 721.4899], device='cuda:0')
cal grad..
tensor([ 815.0453], device='cuda:0')
cal grad..
tensor([ 895.7427], device='cuda:0')
cal grad..
tensor([ 797.1152], device='cuda:0')
cal grad..
tensor([ 614.3089], device='cuda:0')
cal grad..
tensor([ 799.6542], device='cuda:0')
cal grad..
tensor([ 693.3326], device='cuda:0')
cal grad..
tensor([ 702.2778], device='cuda:0')
cal grad..
tensor([ 857.0112], device='cuda:0')
cal grad..
tensor([ 771.6944], device='cuda:0')
cal grad..
tensor([ 753.4550], device='cuda:0')
cal grad..
tensor([ 870.4523], device='cuda:0')
cal grad..
tensor([ 796.2069], device='cuda:0')
cal grad..
tensor([ 805.6575], device='cuda:0')
cal grad..
tensor([ 843.3562], device='cuda:0')
cal grad..
tensor([ 769.8610], device='cuda:0')
cal grad..
tensor([ 787.8606], device='cuda:0')
cal grad..
tensor([ 696.3002], device='cuda:0')
cal grad..
tensor([ 662.7785], device='cuda:0')
cal grad..
tensor([ 696.6882], device='cuda:0')
cal grad..
tensor([ 733.8537], device='cuda:0')
cal grad..
tensor([ 686.6923], device='cuda:0')
cal grad..
tensor([ 676.2560], device='cuda:0')
cal grad..
tensor([ 735.0876], device='cuda:0')
cal grad..
tensor([ 831.0984], device='cuda:0')
cal grad..
tensor([ 803.6078], device='cuda:0')
cal grad..
tensor([ 783.6475], device='cuda:0')
cal grad..
tensor([ 854.4816], device='cuda:0')
cal grad..
tensor([ 722.3654], device='cuda:0')
cal grad..
tensor([ 716.2682], device='cuda:0')
cal grad..
tensor([ 727.2023], device='cuda:0')
cal grad..
tensor([ 704.2264], device='cuda:0')
cal grad..
tensor([ 807.2324], device='cuda:0')
cal grad..
tensor([ 775.9112], device='cuda:0')
cal grad..
tensor([ 848.8185], device='cuda:0')
cal grad..
tensor([ 953.9637], device='cuda:0')
cal grad..
tensor([ 887.9122], device='cuda:0')
cal grad..
tensor([ 903.1782], device='cuda:0')
cal grad..
tensor([ 871.9648], device='cuda:0')
cal grad..
tensor([ 809.6415], device='cuda:0')
cal grad..
tensor([ 763.5831], device='cuda:0')
cal grad..
tensor([ 805.4323], device='cuda:0')
cal grad..
tensor([ 767.7202], device='cuda:0')
cal grad..
tensor([ 827.7583], device='cuda:0')
cal grad..
tensor([ 780.3875], device='cuda:0')
cal grad..
tensor([ 717.5980], device='cuda:0')
cal grad..
tensor([ 650.4529], device='cuda:0')
cal grad..
tensor([ 742.5225], device='cuda:0')
cal grad..
tensor([ 823.7081], device='cuda:0')
cal grad..
tensor([ 839.6797], device='cuda:0')
cal grad..
tensor([ 698.2926], device='cuda:0')
cal grad..
tensor([ 911.0435], device='cuda:0')
cal grad..
tensor([ 808.4606], device='cuda:0')
cal grad..
tensor([ 804.3620], device='cuda:0')
cal grad..
tensor([ 795.7551], device='cuda:0')
cal grad..
tensor([ 808.2845], device='cuda:0')
cal grad..
tensor([ 792.5273], device='cuda:0')
cal grad..
tensor([ 844.9972], device='cuda:0')
cal grad..
tensor([ 803.4642], device='cuda:0')
cal grad..
tensor([ 699.0540], device='cuda:0')
cal grad..
tensor([ 828.3943], device='cuda:0')
cal grad..
tensor([ 724.0145], device='cuda:0')
cal grad..
tensor([ 745.1006], device='cuda:0')
cal grad..
tensor([ 782.4451], device='cuda:0')
cal grad..
tensor([ 741.9065], device='cuda:0')
cal grad..
tensor([ 839.9814], device='cuda:0')
cal grad..
tensor([ 859.3087], device='cuda:0')
cal grad..
tensor([ 697.8011], device='cuda:0')
cal grad..
tensor([ 770.9048], device='cuda:0')
cal grad..
tensor([ 760.1619], device='cuda:0')
cal grad..
tensor([ 780.3185], device='cuda:0')
cal grad..
tensor([ 738.9421], device='cuda:0')
cal grad..
tensor([ 818.8733], device='cuda:0')
cal grad..
tensor([ 830.8091], device='cuda:0')
cal grad..
tensor([ 811.5193], device='cuda:0')
cal grad..
tensor([ 824.3984], device='cuda:0')
cal grad..
tensor([ 659.7209], device='cuda:0')
cal grad..
tensor([ 701.9001], device='cuda:0')
cal grad..
tensor([ 829.2281], device='cuda:0')
cal grad..
tensor([ 794.6914], device='cuda:0')
cal grad..
tensor([ 752.9245], device='cuda:0')
cal grad..
tensor([ 872.0611], device='cuda:0')
cal grad..
tensor([ 914.0952], device='cuda:0')
cal grad..
tensor([ 723.4525], device='cuda:0')
cal grad..
tensor([ 687.8282], device='cuda:0')
cal grad..
tensor([ 780.0715], device='cuda:0')
cal grad..
tensor([ 927.1405], device='cuda:0')
cal grad..
tensor([ 826.3940], device='cuda:0')
cal grad..
tensor([ 629.0449], device='cuda:0')
cal grad..
tensor([ 839.7452], device='cuda:0')
cal grad..
tensor([ 792.7134], device='cuda:0')
cal grad..
tensor([ 774.7518], device='cuda:0')
cal grad..
tensor([ 777.9472], device='cuda:0')
cal grad..
tensor([ 823.4719], device='cuda:0')
cal grad..
tensor([ 807.8542], device='cuda:0')
cal grad..
tensor([ 817.1769], device='cuda:0')
cal grad..
tensor([ 865.3553], device='cuda:0')
new iter
cal grad..
tensor([ 812.3110], device='cuda:0')
cal grad..
tensor([ 784.7684], device='cuda:0')
cal grad..
tensor([ 777.5480], device='cuda:0')
cal grad..
tensor([ 770.4006], device='cuda:0')
cal grad..
tensor([ 704.0202], device='cuda:0')
cal grad..
tensor([ 656.6118], device='cuda:0')
cal grad..
tensor([ 693.8492], device='cuda:0')
cal grad..
tensor([ 754.5069], device='cuda:0')
cal grad..
tensor([ 799.5516], device='cuda:0')
cal grad..
tensor([ 858.1715], device='cuda:0')
cal grad..
tensor([ 762.9025], device='cuda:0')
cal grad..
tensor([ 684.0759], device='cuda:0')
cal grad..
tensor([ 861.0009], device='cuda:0')
cal grad..
tensor([ 693.5399], device='cuda:0')
cal grad..
tensor([ 735.8182], device='cuda:0')
cal grad..
tensor([ 813.3685], device='cuda:0')
cal grad..
tensor([ 904.3801], device='cuda:0')
cal grad..
tensor([ 873.4323], device='cuda:0')
cal grad..
tensor([ 691.0052], device='cuda:0')
cal grad..
tensor([ 817.4833], device='cuda:0')
cal grad..
tensor([ 687.5128], device='cuda:0')
cal grad..
tensor([ 678.9813], device='cuda:0')
cal grad..
tensor([ 830.1082], device='cuda:0')
cal grad..
tensor([ 717.7280], device='cuda:0')
cal grad..
tensor([ 712.3713], device='cuda:0')
cal grad..
tensor([ 831.5644], device='cuda:0')
cal grad..
tensor([ 701.6025], device='cuda:0')
cal grad..
tensor([ 729.9919], device='cuda:0')
cal grad..
tensor([ 806.1777], device='cuda:0')
cal grad..
tensor([ 758.7400], device='cuda:0')
cal grad..
tensor([ 795.6081], device='cuda:0')
cal grad..
tensor([ 709.7166], device='cuda:0')
cal grad..
tensor([ 670.4403], device='cuda:0')
cal grad..
tensor([ 703.3572], device='cuda:0')
cal grad..
tensor([ 751.3612], device='cuda:0')
cal grad..
tensor([ 707.6416], device='cuda:0')
cal grad..
tensor([ 682.2617], device='cuda:0')
cal grad..
tensor([ 741.4466], device='cuda:0')
cal grad..
tensor([ 844.6535], device='cuda:0')
cal grad..
tensor([ 841.9928], device='cuda:0')
cal grad..
tensor([ 812.9803], device='cuda:0')
cal grad..
tensor([ 922.0214], device='cuda:0')
cal grad..
tensor([ 802.0226], device='cuda:0')
cal grad..
tensor([ 711.0294], device='cuda:0')
cal grad..
tensor([ 722.8704], device='cuda:0')
cal grad..
tensor([ 707.9772], device='cuda:0')
cal grad..
tensor([ 799.9745], device='cuda:0')
cal grad..
tensor([ 763.4428], device='cuda:0')
cal grad..
tensor([ 834.6397], device='cuda:0')
cal grad..
tensor([ 939.1743], device='cuda:0')
cal grad..
tensor([ 865.8109], device='cuda:0')
cal grad..
tensor([ 901.2737], device='cuda:0')
cal grad..
tensor([ 871.6179], device='cuda:0')
cal grad..
tensor([ 805.5805], device='cuda:0')
cal grad..
tensor([ 758.4474], device='cuda:0')
cal grad..
tensor([ 799.3937], device='cuda:0')
cal grad..
tensor([ 761.4286], device='cuda:0')
cal grad..
tensor([ 823.4767], device='cuda:0')
cal grad..
tensor([ 778.1305], device='cuda:0')
cal grad..
tensor([ 716.4442], device='cuda:0')
cal grad..
tensor([ 648.7668], device='cuda:0')
cal grad..
tensor([ 740.1150], device='cuda:0')
cal grad..
tensor([ 819.9764], device='cuda:0')
cal grad..
tensor([ 837.0349], device='cuda:0')
cal grad..
tensor([ 694.8442], device='cuda:0')
cal grad..
tensor([ 907.4980], device='cuda:0')
cal grad..
tensor([ 803.0899], device='cuda:0')
cal grad..
tensor([ 799.2672], device='cuda:0')
cal grad..
tensor([ 792.0714], device='cuda:0')
cal grad..
tensor([ 804.0610], device='cuda:0')
cal grad..
tensor([ 787.2267], device='cuda:0')
cal grad..
tensor([ 841.5878], device='cuda:0')
cal grad..
tensor([ 799.8630], device='cuda:0')
cal grad..
tensor([ 695.8910], device='cuda:0')
cal grad..
tensor([ 823.0544], device='cuda:0')
cal grad..
tensor([ 718.8376], device='cuda:0')
cal grad..
tensor([ 741.4748], device='cuda:0')
cal grad..
tensor([ 779.2692], device='cuda:0')
cal grad..
tensor([ 738.5728], device='cuda:0')
cal grad..
tensor([ 836.1926], device='cuda:0')
cal grad..
tensor([ 855.9437], device='cuda:0')
cal grad..
tensor([ 694.7621], device='cuda:0')
cal grad..
tensor([ 768.2972], device='cuda:0')
cal grad..
tensor([ 758.2587], device='cuda:0')
cal grad..
tensor([ 777.9860], device='cuda:0')
cal grad..
tensor([ 736.2917], device='cuda:0')
cal grad..
tensor([ 814.9377], device='cuda:0')
cal grad..
tensor([ 827.2020], device='cuda:0')
cal grad..
tensor([ 809.0521], device='cuda:0')
cal grad..
tensor([ 821.2297], device='cuda:0')
cal grad..
tensor([ 655.7739], device='cuda:0')
cal grad..
tensor([ 698.9956], device='cuda:0')
cal grad..
tensor([ 825.8769], device='cuda:0')
cal grad..
tensor([ 792.5885], device='cuda:0')
cal grad..
tensor([ 749.9053], device='cuda:0')
cal grad..
tensor([ 869.1137], device='cuda:0')
cal grad..
tensor([ 909.3021], device='cuda:0')
cal grad..
tensor([ 720.6742], device='cuda:0')
cal grad..
tensor([ 684.8234], device='cuda:0')
cal grad..
tensor([ 775.6119], device='cuda:0')
cal grad..
tensor([ 920.7389], device='cuda:0')
cal grad..
tensor([ 820.8165], device='cuda:0')
cal grad..
tensor([ 624.7427], device='cuda:0')
cal grad..
tensor([ 836.6601], device='cuda:0')
cal grad..
tensor([ 787.7929], device='cuda:0')
cal grad..
tensor([ 771.4266], device='cuda:0')
cal grad..
tensor([ 774.7710], device='cuda:0')
cal grad..
tensor([ 820.4644], device='cuda:0')
cal grad..
tensor([ 805.1578], device='cuda:0')
cal grad..
tensor([ 813.7911], device='cuda:0')
cal grad..
tensor([ 862.0755], device='cuda:0')
new iter
cal grad..
tensor([ 810.7137], device='cuda:0')
cal grad..
tensor([ 781.6011], device='cuda:0')
cal grad..
tensor([ 774.4418], device='cuda:0')
cal grad..
tensor([ 769.1010], device='cuda:0')
cal grad..
tensor([ 701.7961], device='cuda:0')
cal grad..
tensor([ 659.0839], device='cuda:0')
cal grad..
tensor([ 697.5904], device='cuda:0')
cal grad..
tensor([ 753.8912], device='cuda:0')
cal grad..
tensor([ 798.8121], device='cuda:0')
cal grad..
tensor([ 853.4874], device='cuda:0')
cal grad..
tensor([ 756.8504], device='cuda:0')
cal grad..
tensor([ 676.4562], device='cuda:0')
cal grad..
tensor([ 865.9045], device='cuda:0')
cal grad..
tensor([ 728.5597], device='cuda:0')
cal grad..
tensor([ 779.3145], device='cuda:0')
cal grad..
tensor([ 824.0349], device='cuda:0')
cal grad..
tensor([ 905.6815], device='cuda:0')
cal grad..
tensor([ 869.0866], device='cuda:0')
cal grad..
tensor([ 665.7833], device='cuda:0')
cal grad..
tensor([ 804.8256], device='cuda:0')
cal grad..
tensor([ 681.0598], device='cuda:0')
cal grad..
tensor([ 675.9633], device='cuda:0')
cal grad..
tensor([ 825.9305], device='cuda:0')
cal grad..
tensor([ 716.0402], device='cuda:0')
cal grad..
tensor([ 708.9673], device='cuda:0')
cal grad..
tensor([ 828.1786], device='cuda:0')
cal grad..
tensor([ 713.4258], device='cuda:0')
cal grad..
tensor([ 754.6530], device='cuda:0')
cal grad..
tensor([ 828.4990], device='cuda:0')
cal grad..
tensor([ 776.5013], device='cuda:0')
cal grad..
tensor([ 803.3712], device='cuda:0')
cal grad..
tensor([ 705.4869], device='cuda:0')
cal grad..
tensor([ 660.7144], device='cuda:0')
cal grad..
tensor([ 691.6296], device='cuda:0')
cal grad..
tensor([ 735.0331], device='cuda:0')
cal grad..
tensor([ 684.5385], device='cuda:0')
cal grad..
tensor([ 669.3327], device='cuda:0')
cal grad..
tensor([ 724.4340], device='cuda:0')
cal grad..
tensor([ 822.5150], device='cuda:0')
cal grad..
tensor([ 799.7844], device='cuda:0')
cal grad..
tensor([ 772.0730], device='cuda:0')
cal grad..
tensor([ 866.6682], device='cuda:0')
cal grad..
tensor([ 739.1825], device='cuda:0')
cal grad..
tensor([ 713.2479], device='cuda:0')
cal grad..
tensor([ 721.0527], device='cuda:0')
cal grad..
tensor([ 702.0795], device='cuda:0')
cal grad..
tensor([ 800.2786], device='cuda:0')
cal grad..
tensor([ 771.4858], device='cuda:0')
cal grad..
tensor([ 843.7920], device='cuda:0')
cal grad..
tensor([ 946.6672], device='cuda:0')
cal grad..
tensor([ 874.6909], device='cuda:0')
cal grad..
tensor([ 900.4178], device='cuda:0')
cal grad..
tensor([ 867.2540], device='cuda:0')
cal grad..
tensor([ 801.3623], device='cuda:0')
cal grad..
tensor([ 756.9683], device='cuda:0')
cal grad..
tensor([ 798.1226], device='cuda:0')
cal grad..
tensor([ 758.8547], device='cuda:0')
cal grad..
tensor([ 818.6080], device='cuda:0')
cal grad..
tensor([ 773.4132], device='cuda:0')
cal grad..
tensor([ 711.1499], device='cuda:0')
cal grad..
tensor([ 644.1742], device='cuda:0')
cal grad..
tensor([ 736.3234], device='cuda:0')
cal grad..
tensor([ 815.2866], device='cuda:0')
cal grad..
tensor([ 831.8230], device='cuda:0')
cal grad..
tensor([ 689.6272], device='cuda:0')
cal grad..
tensor([ 901.3661], device='cuda:0')
cal grad..
tensor([ 797.9456], device='cuda:0')
cal grad..
tensor([ 795.7722], device='cuda:0')
cal grad..
tensor([ 789.8690], device='cuda:0')
cal grad..
tensor([ 801.1751], device='cuda:0')
cal grad..
tensor([ 783.8111], device='cuda:0')
cal grad..
tensor([ 839.1475], device='cuda:0')
cal grad..
tensor([ 796.8414], device='cuda:0')
cal grad..
tensor([ 693.7114], device='cuda:0')
cal grad..
tensor([ 819.4617], device='cuda:0')
cal grad..
tensor([ 715.4850], device='cuda:0')
cal grad..
tensor([ 737.9924], device='cuda:0')
cal grad..
tensor([ 777.3370], device='cuda:0')
cal grad..
tensor([ 735.3282], device='cuda:0')
cal grad..
tensor([ 832.9305], device='cuda:0')
cal grad..
tensor([ 853.1224], device='cuda:0')
cal grad..
tensor([ 692.3531], device='cuda:0')
cal grad..
tensor([ 765.1219], device='cuda:0')
cal grad..
tensor([ 754.7258], device='cuda:0')
cal grad..
tensor([ 774.2453], device='cuda:0')
cal grad..
tensor([ 733.7541], device='cuda:0')
cal grad..
tensor([ 811.2035], device='cuda:0')
cal grad..
tensor([ 823.9106], device='cuda:0')
cal grad..
tensor([ 807.5023], device='cuda:0')
cal grad..
tensor([ 818.9177], device='cuda:0')
cal grad..
tensor([ 653.1818], device='cuda:0')
cal grad..
tensor([ 696.5618], device='cuda:0')
cal grad..
tensor([ 822.7280], device='cuda:0')
cal grad..
tensor([ 788.8186], device='cuda:0')
cal grad..
tensor([ 746.0325], device='cuda:0')
cal grad..
tensor([ 865.7122], device='cuda:0')
cal grad..
tensor([ 904.4100], device='cuda:0')
cal grad..
tensor([ 717.4634], device='cuda:0')
cal grad..
tensor([ 681.4001], device='cuda:0')
cal grad..
tensor([ 771.1631], device='cuda:0')
cal grad..
tensor([ 915.3925], device='cuda:0')
cal grad..
tensor([ 816.6349], device='cuda:0')
cal grad..
tensor([ 621.0255], device='cuda:0')
cal grad..
tensor([ 833.3591], device='cuda:0')
cal grad..
tensor([ 783.3322], device='cuda:0')
cal grad..
tensor([ 768.2134], device='cuda:0')
cal grad..
tensor([ 771.8727], device='cuda:0')
cal grad..
tensor([ 817.4695], device='cuda:0')
cal grad..
tensor([ 802.5568], device='cuda:0')
cal grad..
tensor([ 811.1536], device='cuda:0')
cal grad..
tensor([ 859.2676], device='cuda:0')
new iter
cal grad..
tensor([ 807.0493], device='cuda:0')
cal grad..
tensor([ 776.9702], device='cuda:0')
cal grad..
tensor([ 770.6295], device='cuda:0')
cal grad..
tensor([ 766.8334], device='cuda:0')
cal grad..
tensor([ 699.4906], device='cuda:0')
cal grad..
tensor([ 661.2234], device='cuda:0')
cal grad..
tensor([ 701.9105], device='cuda:0')
cal grad..
tensor([ 753.0790], device='cuda:0')
cal grad..
tensor([ 798.6251], device='cuda:0')
cal grad..
tensor([ 849.4792], device='cuda:0')
cal grad..
tensor([ 753.0320], device='cuda:0')
cal grad..
tensor([ 673.5775], device='cuda:0')
cal grad..
tensor([ 874.2253], device='cuda:0')
cal grad..
tensor([ 761.5740], device='cuda:0')
cal grad..
tensor([ 807.4838], device='cuda:0')
cal grad..
tensor([ 824.0927], device='cuda:0')
cal grad..
tensor([ 894.8410], device='cuda:0')
cal grad..
tensor([ 835.1879], device='cuda:0')
cal grad..
tensor([ 633.0226], device='cuda:0')
cal grad..
tensor([ 790.4144], device='cuda:0')
cal grad..
tensor([ 675.8404], device='cuda:0')
cal grad..
tensor([ 672.0871], device='cuda:0')
cal grad..
tensor([ 822.5725], device='cuda:0')
cal grad..
tensor([ 713.5005], device='cuda:0')
cal grad..
tensor([ 705.7325], device='cuda:0')
cal grad..
tensor([ 825.2354], device='cuda:0')
cal grad..
tensor([ 717.0671], device='cuda:0')
cal grad..
tensor([ 760.8139], device='cuda:0')
cal grad..
tensor([ 828.4405], device='cuda:0')
cal grad..
tensor([ 771.9101], device='cuda:0')
cal grad..
tensor([ 797.0662], device='cuda:0')
cal grad..
tensor([ 698.8149], device='cuda:0')
cal grad..
tensor([ 654.8073], device='cuda:0')
cal grad..
tensor([ 686.7063], device='cuda:0')
cal grad..
tensor([ 730.0911], device='cuda:0')
cal grad..
tensor([ 678.4540], device='cuda:0')
cal grad..
tensor([ 665.8056], device='cuda:0')
cal grad..
tensor([ 719.3838], device='cuda:0')
cal grad..
tensor([ 817.6150], device='cuda:0')
cal grad..
tensor([ 793.1920], device='cuda:0')
cal grad..
tensor([ 768.3682], device='cuda:0')
cal grad..
tensor([ 849.5177], device='cuda:0')
cal grad..
tensor([ 716.7332], device='cuda:0')
cal grad..
tensor([ 706.9028], device='cuda:0')
cal grad..
tensor([ 718.2142], device='cuda:0')
cal grad..
tensor([ 694.4294], device='cuda:0')
cal grad..
tensor([ 795.2200], device='cuda:0')
cal grad..
tensor([ 768.2627], device='cuda:0')
cal grad..
tensor([ 839.1055], device='cuda:0')
cal grad..
tensor([ 942.1742], device='cuda:0')
cal grad..
tensor([ 872.3578], device='cuda:0')
cal grad..
tensor([ 900.7438], device='cuda:0')
cal grad..
tensor([ 865.1172], device='cuda:0')
cal grad..
tensor([ 798.7148], device='cuda:0')
cal grad..
tensor([ 754.0490], device='cuda:0')
cal grad..
tensor([ 795.5426], device='cuda:0')
cal grad..
tensor([ 756.4938], device='cuda:0')
cal grad..
tensor([ 815.1652], device='cuda:0')
cal grad..
tensor([ 770.0632], device='cuda:0')
cal grad..
tensor([ 707.9734], device='cuda:0')
cal grad..
tensor([ 641.0272], device='cuda:0')
cal grad..
tensor([ 733.6548], device='cuda:0')
cal grad..
tensor([ 812.8312], device='cuda:0')
cal grad..
tensor([ 829.5146], device='cuda:0')
cal grad..
tensor([ 687.4554], device='cuda:0')
cal grad..
tensor([ 898.6711], device='cuda:0')
cal grad..
tensor([ 795.2928], device='cuda:0')
cal grad..
tensor([ 793.5947], device='cuda:0')
cal grad..
tensor([ 788.6101], device='cuda:0')
cal grad..
tensor([ 798.7196], device='cuda:0')
cal grad..
tensor([ 780.6952], device='cuda:0')
cal grad..
tensor([ 837.0511], device='cuda:0')
cal grad..
tensor([ 793.9055], device='cuda:0')
cal grad..
tensor([ 691.6257], device='cuda:0')
cal grad..
tensor([ 816.0581], device='cuda:0')
cal grad..
tensor([ 712.3866], device='cuda:0')
cal grad..
tensor([ 734.6429], device='cuda:0')
cal grad..
tensor([ 775.5750], device='cuda:0')
cal grad..
tensor([ 732.2691], device='cuda:0')
cal grad..
tensor([ 829.7743], device='cuda:0')
cal grad..
tensor([ 850.1251], device='cuda:0')
cal grad..
tensor([ 689.8839], device='cuda:0')
cal grad..
tensor([ 762.0426], device='cuda:0')
cal grad..
tensor([ 751.6131], device='cuda:0')
cal grad..
tensor([ 770.8386], device='cuda:0')
cal grad..
tensor([ 731.2797], device='cuda:0')
cal grad..
tensor([ 807.8104], device='cuda:0')
cal grad..
tensor([ 820.7771], device='cuda:0')
cal grad..
tensor([ 806.0094], device='cuda:0')
cal grad..
tensor([ 816.7054], device='cuda:0')
cal grad..
tensor([ 650.7134], device='cuda:0')
cal grad..
tensor([ 694.0115], device='cuda:0')
cal grad..
tensor([ 819.4715], device='cuda:0')
cal grad..
tensor([ 785.1557], device='cuda:0')
cal grad..
tensor([ 742.4697], device='cuda:0')
cal grad..
tensor([ 862.4937], device='cuda:0')
cal grad..
tensor([ 899.7634], device='cuda:0')
cal grad..
tensor([ 714.7154], device='cuda:0')
cal grad..
tensor([ 678.4197], device='cuda:0')
cal grad..
tensor([ 767.1401], device='cuda:0')
cal grad..
tensor([ 910.1931], device='cuda:0')
cal grad..
tensor([ 812.6218], device='cuda:0')
cal grad..
tensor([ 617.7137], device='cuda:0')
cal grad..
tensor([ 830.2373], device='cuda:0')
cal grad..
tensor([ 779.2676], device='cuda:0')
cal grad..
tensor([ 765.2501], device='cuda:0')
cal grad..
tensor([ 769.1678], device='cuda:0')
cal grad..
tensor([ 814.5136], device='cuda:0')
cal grad..
tensor([ 800.0908], device='cuda:0')
cal grad..
tensor([ 808.4917], device='cuda:0')
cal grad..
tensor([ 856.5182], device='cuda:0')